### ISSUE TITLE
I can't make a plugin

### ISSUE THREAD

**Issue by Blubberboy333** [PocketMine/DevTools#12]
I have a problem. I have been working on my first plugin, and using DevTools has helped me a lot. But when I do /makeplugin PlayerClones_v1.0.0 is says "Invalid plugin name, check the name case." I am 100% sure I am spelling it right. I even copied and pasted the name of the plugin and it still didn't work. Please help.

**Comment by shoghicp** [comment]
You need the exact name of the plugin, not the version. If the name defined in plugin.yml is `My Random Plugin` you'll have to do `/makeplugin My Random Plugin`
