### ISSUE TITLE
Bug with makeplugin Command in v1.10.0

### ISSUE THREAD

**Issue by ghost** [PocketMine/DevTools#17]
I have API 1.13.1 and  v1.10.0 and got this bug when I run makeplugin
`Unknown Error while running command 'makeplugin Engine' in makeplugin: creating archive "test" disabled by the php.ini setting phar.readonly

CRITICAL:
UnexpectedValueException: "creating archive "test" diabled by the php.ini setting phar.readonly" (EXCEPTION) in "/plugin-515.phar/src/DevTools/DevTools" at line 161 `

**Comment by PEMapModder** [comment]
Start the server with option -dphar.readonly=0, or add the line `phar.readonly=0` to PHP.ini

**Comment by ghost** [comment]
Thanks, it's working
