### ISSUE TITLE
Could not load plugin 'MyPlugin'

### ISSUE THREAD

**Issue by BuddyAW** [PocketMine/DevTools#18]
ok so i am trying to make a new plugin with the dev tool i got a really cheep server from a hosting co and i put the plugin devtools on it all i have so far on the plugin is just a bace but when i try to see if it works i get the error "Could not load plugin 'MyPlugin" i used the Plugin Tutorial [here](https://github.com/PocketMine/Documentation/wiki/Plugin-Tutorial) but its just not working please help ASAP! 

Thanks BuddyAW

**Comment by BuddyAW** [comment]
stil cant find any reason its not working

**Comment by applqpak** [comment]
What's your code?

And, do you have the (correct) plugin.yml?

**Comment by BuddyAW** [comment]
<?php

namespace BuddyAW\MyPlugin;

use pocketmine\plugin\PluginBase;

class MyPlugin extends Pluginbace{

}

thats MyPlugin.php

plugin.yml

name: MyPlugin
main: BuddyAW\MyPlugin\MyPlugin
version: 1.0.0
api: 2.0.0

**Comment by applqpak** [comment]
okay, it should be `extends PluginBase` and not `extends PluginBace`

**Comment by BuddyAW** [comment]
where do i put that i dont see what your talking about

**Comment by BuddyAW** [comment]
oh wait i see now

**Comment by applqpak** [comment]
Yep.

**Comment by BuddyAW** [comment]
its still throwing up a error when i try and load it

**Comment by BuddyAW** [comment]
21.08 02:47:22 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 02:47:22 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 02:47:22 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 02:47:22 [Multicraft] Auto-saving world...
21.08 02:37:19 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 02:37:19 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 02:37:19 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 02:37:19 [Multicraft] Auto-saving world...
21.08 02:28:07 [Server] Server thread/INFO Invalid plugin name, check the name case.
21.08 02:27:50 [Multicraft] Skipped 3 lines due to rate limit (30/s)
21.08 02:27:17 [Server] Startup Done (0.397s)! For help, type "help" or "?"
21.08 02:27:17 [Server] Server thread/INFO Query running on 23.91.4.66:44915
21.08 02:27:17 [Server] Server thread/INFO Setting query port to 44915
21.08 02:27:17 [Server] Server thread/INFO Starting GS4 status listener
21.08 02:27:17 [Server] Server thread/INFO Loading...
21.08 02:27:17 [Server] Server thread/INFO Enabling EssentialsPE v2.0.0-php7
21.08 02:27:17 [Server] Server thread/INFO Preparing level "nether"
21.08 02:27:17 [Server] Server thread/INFO Preparing level "world"
21.08 02:27:17 [Server] Server thread/INFO Registered folder plugin loader
21.08 02:27:17 [Server] Server thread/CRITICAL Could not load plugin 'MyPlugin'
21.08 02:27:17 [Server] Server thread/INFO Enabling DevTools v1.10.0
21.08 02:27:17 [Server] Server thread/CRITICAL Could not load plugin 'MyPlugin'
21.08 02:27:17 [Server] Server thread/INFO Loading EssentialsPE v2.0.0-php7
21.08 02:27:17 [Server] Server thread/INFO Loading DevTools v1.10.0
21.08 02:27:17 [Server] Server thread/INFO Genisys is distributed under the GPL License version 3 and later
21.08 02:27:17 [Server] INFO sh: ifconfig: command not found
21.08 02:27:17 [Server] INFO sh: ifconfig: command not found
21.08 02:27:17 [Server] Server thread/INFO Opening server on 23.91.4.66:44915
21.08 02:27:17 [Server] Server thread/INFO Selected English (eng) as the base language
21.08 02:27:17 [Server] Server thread/INFO Loading server properties...
21.08 02:27:17 [Server] Server thread/WARNING You are using an unsupported build. Do not use this build in a production environment.
21.08 02:27:17 [Server] INFO Source code: https://github.com/iTXTech/Genisys
21.08 02:27:17 [Server] INFO Target client version: v0.15.4 alpha
21.08 02:27:17 [Server] INFO Version: unsupported-831a443
21.08 02:27:17 [Server] INFO Genisys is a fork of PocketMine-MP, made by iTX Technologies LLC
21.08 02:27:17 [Server] INFO Launching mod. Please be patient...
21.08 02:27:17 [Multicraft] Failed to copy jarfile from global JAR directory
21.08 02:27:17 [Multicraft] JAR file not found, copying from global JAR directory
21.08 02:27:17 [Multicraft] Failed to create local JAR directory
21.08 02:27:17 [Multicraft] Loaded config for "_Minecraft Pocket% Genisys% MCPE 0.15.4 - API 2.0.0 - PHP7.0.3 (Auto Update)% MCPE v0.15.4 Alpha% 192% <a href="https://github.com/iTXTech/Genisys/blob/master/README.md">Genisys</a> has <b>Mobs w/AI, Redstone, Weather, Potions, and more!<br \><br \><font color="Red">WARNING: YOUR PLUGINS WILL NOT LOAD</font> unless they have been updated for PHP 7!<br \><br \>This pack includes SimpleAuth + Helper and EssentialsPE, all patched for PHP7.<br \><br \><font size="+1" color="#08C0FC"><b>AUTO Update!<b></font><br>Just restart your server to use the latest, tested build of Genisys."
21.08 02:27:17 [Multicraft] Starting server!
21.08 02:27:17 [Multicraft] Loading server properties
21.08 02:27:17 [Multicraft] Server stopped
21.08 02:27:17 [Multicraft] Server shut down
21.08 02:27:16 [Server] INFO Server has stopped
21.08 02:27:16 [Server] Server thread/INFO Stopping other threads
21.08 02:27:16 [Server] Server thread/INFO Unloading level "nether"
21.08 02:27:16 [Server] Server thread/INFO Unloading level "world"
21.08 02:27:16 [Server] Server thread/INFO Disabling EssentialsPE v2.0.0-php7
21.08 02:27:16 [Server] Server thread/INFO Disabling DevTools v1.10.0
21.08 02:27:16 [Server] Server thread/INFO [CONSOLE: Stopping the server]
21.08 02:27:16 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 02:27:16 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 02:27:16 [Multicraft] Stopping server!
21.08 02:27:16 [Multicraft] Received restart command
21.08 02:22:36 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 02:22:36 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 02:22:36 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 02:22:36 [Multicraft] Auto-saving world...
21.08 02:12:33 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 02:12:33 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 02:12:33 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 02:12:33 [Multicraft] Auto-saving world...
21.08 02:02:30 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 02:02:30 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 02:02:30 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 02:02:30 [Multicraft] Auto-saving world...
21.08 01:52:28 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 01:52:28 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 01:52:28 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 01:52:28 [Multicraft] Auto-saving world...
21.08 01:42:25 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 01:42:25 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 01:42:25 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 01:42:25 [Multicraft] Auto-saving world...
21.08 01:32:22 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 01:32:22 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 01:32:22 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 01:32:22 [Multicraft] Auto-saving world...
21.08 01:22:20 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 01:22:20 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 01:22:20 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 01:22:20 [Multicraft] Auto-saving world...
21.08 01:12:17 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 01:12:17 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 01:12:17 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 01:12:17 [Multicraft] Auto-saving world...
21.08 01:02:14 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 01:02:14 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 01:02:14 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 01:02:14 [Multicraft] Auto-saving world...
21.08 00:52:12 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 00:52:12 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 00:52:12 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 00:52:12 [Multicraft] Auto-saving world...
21.08 00:42:09 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 00:42:09 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 00:42:09 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 00:42:09 [Multicraft] Auto-saving world...
21.08 00:32:06 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 00:32:06 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 00:32:06 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 00:32:06 [Multicraft] Auto-saving world...
21.08 00:22:03 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 00:22:03 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 00:22:03 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 00:22:03 [Multicraft] Auto-saving world...
21.08 00:12:01 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 00:12:01 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 00:12:01 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 00:12:01 [Multicraft] Auto-saving world...
21.08 00:01:58 [Server] Server thread/INFO [CONSOLE: Saved the world]
21.08 00:01:58 [Server] Server thread/INFO [CONSOLE: Saving...]
21.08 00:01:58 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
21.08 00:01:58 [Multicraft] Auto-saving world...
20.08 23:51:55 [Server] Server thread/INFO [CONSOLE: Saved the world]
20.08 23:51:55 [Server] Server thread/INFO [CONSOLE: Saving...]
20.08 23:51:55 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
20.08 23:51:55 [Multicraft] Auto-saving world...
20.08 23:41:53 [Server] Server thread/INFO [CONSOLE: Saved the world]

console chat log

**Comment by BuddyAW** [comment]
still haveing a problem

**Comment by thelucyclub** [comment]
try using pmmp insteaad of genisys.
