### ISSUE TITLE
Issue with making a php file in new dev tools v1.11.0

### ISSUE THREAD

**Issue by BlueishDesert78** [PocketMine/DevTools#23]
Can't setup a php file by making a plugin with Dev tools v1.11.0 for php7

**Comment by BlueishDesert78** [comment]
Here is my console text 

[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [17:56:41] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [17:56:41] [Server thread/INFO]: 
[Server] 
[Server] 	Genisys is a custom version of PocketMine-MP ,modified by iTX Technologies LLC & birdkkk
[Server] 	Version: 2.2 dev
[Server] 	Target client version: v1.0.4.11
[Server] 	Source code: https://github.com/iTXTech/Genisys
[Server] 	Upload by: https://www.facebook.com/mcpeplugin
[Server] 	Edit by: birdkkk
[Server] 	
[Server] [17:56:41] [Server thread/INFO]: Loading properties and configuration...
[Server] [17:56:41] [Server thread/WARNING]: The OpenSSL extension is not loaded, and this is required for XBOX authentication to work. If you want to use Xbox Live auth, please update your PHP binaries at itxtech.org/genisys/get/, or recompile PHP with the OpenSSL extension.
[Server] [17:56:41] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [17:56:41] [Server thread/INFO]: Starting remote control listener
[Server] [17:56:42] [Server thread/INFO]: RCON running on 0.0.0.0:19131
[Server] [17:56:42] [Server thread/WARNING]: Debugging assertions are enabled, this may impact on performance. To disable them, set `zend.assertions = -1` in php.ini.
[Server] [17:56:42] [Server thread/INFO]: Opening server on 0.0.0.0:19131
[Server] [17:56:42] [Server thread/INFO]: Genisys is distributed under the GPL License version 3 and later
[Server] [17:56:42] [Server thread/INFO]: Loading recipes...
[Server] [17:56:43] [Server thread/ERROR]: Could not load plugin 'DevTools': Incompatible API version
[Server] [17:56:43] [Server thread/INFO]: Loading DevTools v1.11.0
[Server] [17:56:43] [Server thread/INFO]: Loading iProtector v3.1b
[Server] [17:56:43] [Server thread/INFO]: Loading Lightning_Strike v2
[Server] [17:56:43] [Server thread/INFO]: [Lightning_Strike] Preparing For StartUp... STAND BY
[Server] [17:56:43] [Server thread/INFO]: Loading GodMode v2.4
[Server] [17:56:43] [Server thread/INFO]: Enabling DevTools v1.11.0
[Server] [17:56:43] [Server thread/INFO]: Loading source plugin SignShop v1.0.0
[Server] [17:56:43] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected 'public' (T_PUBLIC), expecting '{'" (EXCEPTION) in "/SignShop/src/SignShop/SignShop" at line 10
[Server] [17:56:43] [Server thread/INFO]: Disabling DevTools v1.11.0
[Server] [17:56:43] [Server thread/INFO]: Preparing level "Aeon Gears - Breeze 2"
[Server] [17:56:43] [Server thread/INFO]: Enabling iProtector v3.1b
[Server] [17:56:43] [Server thread/INFO]: Enabling Lightning_Strike v2
[Server] [17:56:43] [Server thread/INFO]: [Lightning_Strike] Lightning Strike RUNNING Made By MichaelM04
[Server] [17:56:43] [Server thread/INFO]: Enabling GodMode v2.4
[Server] [17:56:43] [Server thread/NOTICE]: Your genisys.yml needs update
[Server] [17:56:43] [Server thread/NOTICE]: Current Version: 22 Latest Version: 24
[Server] [17:56:43] [Server thread/INFO]: Starting GS4 status listener
[Server] [17:56:43] [Server thread/INFO]: Setting query port to 19131
[Server] [17:56:43] [Server thread/INFO]: Query running on 0.0.0.0:19131
[Server] [17:56:43] [Server thread/INFO]: Default game type: Creative Mode
[Server] [17:56:43] [Server thread/INFO]: Done (7.597s)! For help, type "help" or "?"

**Comment by ghost** [comment]
@BlueishDesert78 here is the new repo: https://github.com/pmmp/PocketMine-DevTools
