### ISSUE TITLE
Bug at server "Reload"

### ISSUE THREAD

**Issue by iksaku** [PocketMine/DevTools#5]
Hi there!

I think that I already reported this a month ago, but anyway here it is:

While you develop plugins and use DevTools to load the source (to debug) everythin is fine, but when you reload the server (`/reload`) DevTools reload perfectly, but it doesn't load again the source code style plugins.

Thanks!

**Comment by ishitatsuyuki** [comment]
The bug is caused by php specification. PHP DOESN'T support class unload, we need to add runkit support to pocketmine (and api). @shoghicp

**Comment by LDX-MCPE** [comment]
I have the same problem. That would make plugin development so easy.

**Comment by china-richway2** [comment]
@shoghicp
FolderPluginLoader DOES work but DevTools DOES NOT work.
When reload is called, DevTools is enabled, but all the source plugins are not re-enabled.
https://github.com/PocketMine/DevTools/commit/0d6c9db2a8b5d6774a181a0fff8392bc60ddf07c gives the exact fix.

**Comment by robske110** [comment]
Why has that been detached

**Comment by FNAFMCPLYZ** [comment]
I maked my own Plugin but it says source Plugin can't load

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-DevTools/commit/cafa01f1351c64a945d0022fbe58fe687fdf06fc fixes this.
